### ISSUE TITLE
Failed to generate 3D mesh 

### ISSUE THREAD

**Issue by toyxyz** [zjp-shadow/CharacterGen#11]
I had no problem generating the 4 view, but when I tried to generate a 3D mesh, I got the following error 

[Open3D INFO] actual parallel_partitions 1
UV unwrapping o3d: 7232.54ms
Exporting textures ...
Query color: 24.86ms
CVCUDA not available, fallback to CPU UV padding.
UV padding: 153.68ms
Traceback (most recent call last):
  File "C:\Users\toyxy\CharacterGen\venv\lib\site-packages\gradio\queueing.py", line 541, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\toyxy\CharacterGen\venv\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\toyxy\CharacterGen\venv\lib\site-packages\gradio\blocks.py", line 1928, in process_api
    result = await self.call_function(
  File "C:\Users\toyxy\CharacterGen\venv\lib\site-packages\gradio\blocks.py", line 1514, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\toyxy\CharacterGen\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\toyxy\CharacterGen\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\Users\toyxy\CharacterGen\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\Users\toyxy\CharacterGen\venv\lib\site-packages\gradio\utils.py", line 833, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\toyxy\CharacterGen\webui.py", line 338, in process_images
    exporter_output = self.system.exporter([f"{i:02d}" for i in range(rgb_cond.shape[0])], scene_codes)
  File "C:\Users\toyxy\CharacterGen\3D_Stage\lrm\models\exporters\mesh_exporter.py", line 171, in __call__
    output = self.export_model_with_mtl(
  File "C:\Users\toyxy\CharacterGen\3D_Stage\lrm\models\exporters\mesh_exporter.py", line 216, in export_model_with_mtl
    np.savez(f"{self.cfg.output_path}/tex_info.npz", v_tex=mesh.v_tex.cpu().numpy(), t_tex_idx=mesh.t_tex_idx.cpu().numpy())
  File "C:\Users\toyxy\CharacterGen\venv\lib\site-packages\numpy\lib\npyio.py", line 639, in savez
    _savez(file, args, kwds, False)
  File "C:\Users\toyxy\CharacterGen\venv\lib\site-packages\numpy\lib\npyio.py", line 736, in _savez
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "C:\Users\toyxy\CharacterGen\venv\lib\site-packages\numpy\lib\npyio.py", line 103, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "C:\Users\toyxy\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: './3D_Stage/outputs/tex_info.npz'

**Comment by MrForExample** [comment]
I got the same error, and I solved it by adding `os.makedirs(self.cfg.output_path, exist_ok=True)` before line 216 in mesh_exporter.py

**Comment by toyxyz** [comment]
> @toyxyz Yo, what's up, nice to see you here :) I got the same error, and I solved it by adding `os.makedirs(self.cfg.output_path, exist_ok=True)` before line 216 in mesh_exporter.py

Hi! I fixed the problem by modifying `sav_dir` on line 340 of webui.py.
